# Generated by Django 5.2.7 on 2025-10-28 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("DOCTOR", "DOCTOR"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "clinic_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("clinic_address", models.TextField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("available_days", models.JSONField(blank=True, default=list)),
                ("available_time_start", models.TimeField(blank=True, null=True)),
                ("available_time_end", models.TimeField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
