# Generated by Django 5.2.7 on 2025-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_name_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
