# Generated by Django 5.2.7 on 2025-11-10 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="doctorprofile",
            old_name="available_days",
            new_name="languages_spoken",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="available_time_end",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="available_time_start",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="degrees",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="popularity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.specialization",
            ),
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="user.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor", "day", "start_time"],
                "unique_together": {("doctor", "day", "start_time", "end_time")},
            },
        ),
    ]
