# Generated by Django 5.2.7 on 2025-12-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_specialization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDateAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration", models.PositiveIntegerField(default=30)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_availabilities",
                        to="user.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor", "date", "start_time"],
                "unique_together": {("doctor", "date", "start_time", "end_time")},
            },
        ),
    ]
