# Generated by Django 5.2.7 on 2026-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_doctordateavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
